### ISSUE TITLE
TODO: 交互改进

### ISSUE THREAD

**Issue by iamwyh2019** [iamwyh2019/custom-HoshinoBot#2]
目前无论是机器人本体还是插件，每个触发词都有专门功能，一旦命令一多，使用起来对用户很不友好。

例如，表情生成器里“查看表情 [名字]”查看单个表情，“表情列表”查看表情列表，但是许多用户会尝试用“查看表情”查看列表，得到报错后再尝试其它命令。类似的例子还有clanrank的“查询排名”和“查询公会”，clanbattle的“查刀”和“出刀记录”。

基于两个月以来运营bot的经验，我打算稍微改进机器人的交互，包括两点：

- 对于某些错误输入，如果能确定用户的意图，则调用目标功能。例如“查看表情”未接收到名字时调用列举所有表情的功能。
- 不能确定用户意图，或者技术上难以实现时，在报错提示中给出建议。

TODO list：

- 公会战clanbattle
  - [x] 触发“查刀”时，若指定了at，或指定了Boss编号或周目数，则会调用“出刀记录”
- 表情生成器memegenerator
  - [x] 触发“查看表情”时，若名字留空，则调用“表情列表”
  - [x] 触发“生成表情”时，若未传入内容，则直接返回该表情
- 公会战排名clanrank
  - [x] 触发“查询排名”时，若传入的排名不是数字，则尝试查询公会名
  - [x] 触发“查询公会”时，若传入的名字是纯数字，提示用户可能想用“查询排名”
